###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:      
    webserver:
        container_name: geoapi-webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9999:80'

    php-fpm:
        container_name: geoapi-php-fpm
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
